FROM python:3.11-slim-trixie

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the project into the image
ADD /ac2_backend /ac2_backend

# Sync the project into a new environment, asserting the lockfile is up to date
WORKDIR /ac2_backend

EXPOSE 8000

RUN uv sync --locked

CMD ["uv", "run", "fastapi", "run", "backend.py"]
