const fs = require('fs');
const path = require('path');

const configsDir = path.join(__dirname, '../blog/configs');
const dataDir = path.join(__dirname, '../src/app/blog');
const dataFile = path.join(dataDir, 'data.ts');
const useCasesFile = path.join(dataDir, 'useCases.ts');

// Ensure directories exist
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

// Read all JSON config files
const configFiles = fs.readdirSync(configsDir).filter(file => file.endsWith('.json'));

console.log(`Found ${configFiles.length} blog post configs`);

// Read all blog posts
const allPosts = configFiles.map(file => {
  const configPath = path.join(configsDir, file);
  return JSON.parse(fs.readFileSync(configPath, 'utf-8'));
}).sort((a, b) => {
  // Parse dates in format "Month Day, Year" (e.g., "November 22, 2025")
  const dateA = new Date(a.date);
  const dateB = new Date(b.date);
  // Sort descending (newest first)
  return dateB.getTime() - dateA.getTime();
});

// Generate TypeScript data file
const dataContent = `// This file is auto-generated by build-blog.js
// Do not edit manually

export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  description: string;
  content: string;
}

export const blogPosts: BlogPost[] = ${JSON.stringify(allPosts, null, 2)};

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find(post => post.slug === slug);
}
`;

fs.writeFileSync(dataFile, dataContent);
console.log(`Generated blog data file with ${allPosts.length} posts`);

// Generate use cases data for homepage
// Map of slugs to their descriptions from blog configs
const useCasesMap = {};
allPosts.forEach(post => {
  useCasesMap[post.slug] = {
    description: post.description
  };
});

const useCasesContent = `// This file is auto-generated by build-blog.js
// Do not edit manually

export interface UseCaseDescription {
  description: string;
}

export const useCaseDescriptions: Record<string, UseCaseDescription> = ${JSON.stringify(useCasesMap, null, 2)};

export function getUseCaseDescription(slug: string): string | undefined {
  return useCaseDescriptions[slug]?.description;
}
`;

fs.writeFileSync(useCasesFile, useCasesContent);
console.log(`Generated use cases data file`);

console.log('Blog build complete!');
