// This file is auto-generated by build-blog.js
// Do not edit manually

export interface BlogPost {
  slug: string;
  title: string;
  date: string;
  excerpt: string;
  description: string;
  content: string;
}

export const blogPosts: BlogPost[] = [
  {
    "slug": "speaking-truth-to-power",
    "title": "Speaking Truth to Power",
    "date": "January 17, 2025",
    "excerpt": "Harvey Weinstein's victims knew they weren't alone, but each woman feared going public without others. The first to speak out faced the full weight of his power and disbelief.",
    "description": "How anonymous credible commitments can help victims of abuse coordinate coming forward, ensuring they're not alone when they speak out.",
    "content": "<p>Harvey Weinstein's victims knew they weren't alone, but each woman feared going public without others. The first to speak out faced the full weight of his power and disbelief.</p>\n\n<h2>The Isolation Problem</h2>\n<p>Victims of abuse often know they're not alone, but fear the consequences of speaking out individually. The first person to come forward faces disbelief, legal threats, and social isolation, while the abuser uses their power to silence and discredit them.</p>\n\n<h2>Coordinated Disclosure</h2>\n<p>Anonymous credible commitments allow victims to commit to coming forward, setting their own threshold for when they're willing to be revealed. One victim might set their threshold at 5 commitments, while another might need 20. When enough victims have committed, everyone who set a threshold below that number is revealed together.</p>\n\n<h2>Strength in Unity</h2>\n<p>This approach ensures that victims are never alone when they speak out. By coordinating their disclosure, victims can overcome the power imbalance that keeps abuse hidden, transforming individual fear into collective courage.</p>"
  },
  {
    "slug": "political-change",
    "title": "Political Change",
    "date": "January 16, 2025",
    "excerpt": "Citizens in an authoritarian regime oppose the government but won't speak out unless they know the majority shares their views. Fear of being the only dissenter keeps everyone silent.",
    "description": "How anonymous credible commitments enable political dissent in authoritarian regimes by allowing citizens to coordinate without fear.",
    "content": "<p>Citizens in an authoritarian regime oppose the government but won't speak out unless they know the majority shares their views. Fear of being the only dissenter keeps everyone silent.</p>\n\n<h2>The Silence Problem</h2>\n<p>In authoritarian regimes, expressing dissent is dangerous. Individuals who speak out alone face severe consequences, while the regime benefits from the perception that opposition is minimal. This creates a coordination trap where everyone wants change but no one acts.</p>\n\n<h2>Breaking the Silence</h2>\n<p>Anonymous credible commitments allow citizens to express their opposition privately, committing to public action only when enough others have also committed. A student might set their threshold at 10,000 commitments, while a journalist might need 50,000. When the threshold is reached, all committed individuals are revealed together.</p>\n\n<h2>Safety in Numbers</h2>\n<p>This approach provides the safety in numbers that makes political change possible. Citizens can coordinate their opposition without exposing themselves to individual risk, transforming silent discontent into visible collective action.</p>"
  },
  {
    "slug": "labor-organizing",
    "title": "Labor Organizing",
    "date": "January 15, 2025",
    "excerpt": "Amazon workers want to unionize, but only if they know 10,000+ others will join them. Without this certainty, individuals risk retaliation while the effort fails.",
    "description": "How anonymous credible commitments can help workers coordinate unionization efforts without exposing individuals to retaliation.",
    "content": "<p>Amazon workers want to unionize, but only if they know 10,000+ others will join them. Without this certainty, individuals risk retaliation while the effort fails.</p>\n\n<h2>The Challenge</h2>\n<p>Labor organizing faces a fundamental coordination problem. Workers want to unionize, but each individual fears being the only one to take action. Companies have powerful incentives to prevent unionization and can target early organizers with retaliation, making it dangerous to be the first to commit publicly.</p>\n\n<h2>How Anonymous Credible Commitments Help</h2>\n<p>With AC2, workers can commit to unionization privately, setting their own threshold for when they're willing to be revealed. A warehouse worker might set their threshold at 1,000 commitments, while a delivery driver might need 5,000. When enough workers have committed, everyone who set a threshold below that number is revealed simultaneously.</p>\n\n<h2>The Power of Collective Action</h2>\n<p>This transforms unionization from a risky individual decision into a coordinated collective action. Workers know that if they commit, they'll only be revealed when enough others have also committed, providing the safety in numbers that makes organizing possible.</p>"
  }
];

export function getBlogPostBySlug(slug: string): BlogPost | undefined {
  return blogPosts.find(post => post.slug === slug);
}
