// This file is auto-generated by build-blog.js
// Do not edit manually

export interface UseCaseDescription {
  description: string;
}

export const useCaseDescriptions: Record<string, UseCaseDescription> = {
  "political-change": {
    "description": "How anonymous credible commitments can help citizens and politians coordinate their efforts to bring about change, despite power structures which seek to suppress dissent."
  },
  "speaking-truth-to-power": {
    "description": "Victims of abuse, whistleblowers, and other groups who wish to expose wrongdoing often face disbelief, isolation, and legal threats. Anonymous credible commitments can help them coordinate their efforts to expose wrongdoing."
  },
  "ai-pause": {
    "description": "Frontier AI labs have been racing to develop powerful AI models, and have publicly stated that development should be paused until we can guarantee their safety."
  },
  "labor-organizing": {
    "description": "How anonymous credible commitments can help workers coordinate unionization efforts without exposing individuals to retaliation."
  },
  "mathematical-details": {
    "description": "Mathematical foundations and cryptographic guarantees of the AC2 system, with ID verification and decentralised decryption."
  }
};

export function getUseCaseDescription(slug: string): string | undefined {
  return useCaseDescriptions[slug]?.description;
}
